version: '3.8'
services:
  db:
    container_name: vim-db
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=lets_run
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
    ports:
      - '3306:3306'
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - vim-net
  api:
    container_name: vim-api
    build: .
    ports:
      - '9001:9001'
    restart: on-failure
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: mauFJcuf5dhRMQrjj
      DB_NAME: lets_run
    depends_on:
      - db
    networks:
      - vim-net
    volumes:
      - ./:/src
volumes:
  db:
    driver: local


networks:
  vim-net:
    driver: bridge